[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Pro-T-Omics"
authors = [{name = "Team 4", email = "parkinsonsdataanalysis@gmail.com"}]
dynamic = ["version", "description"]